var name = "Kayla";
var greeting = "Hello world!";
var feeling = "happy";
var age = 38
var numberOfPets = 6
var birthYear = 1983
var employed = false
var inSchool = true
var lovesCats = true
var catNames = ['Seven', 'Potato', 'Loki']
var sevenAttributes = ['tabby', 5, 'loves outdoors']
var ages = [5, 1, 3]
var self = {name: 'Kayla', age: 38, occupation: 'Student'}
var car = {make: 'Nissan', model: 'Leaf', year: 2021}
var favoriteMusic = {artist: 'Ben Folds', album: 'Rockin the Suburbs', song: 'Still Fighting It'}
